theme: jekyll-theme-cayman

title: Schüler-Roboter
description: Der programmierbare Roboter für Schüler jeden Alters
lang: de
google_analytics: UA-109840814-3

# generate _posts that seem to be in the future
future: true
